services:
  ldap:
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=SigmaNet
      - LDAP_DOMAIN=sigmanet.site
      - LDAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - type: bind
        source: ./ldap/data/slapd/database
        target: /var/lib/ldap
      - type: bind
        source: ./ldap/data/slapd/config
        target: /etc/ldap/slapd.d
  ldap_admin:
    image: osixia/phpldapadmin
    ports: 
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./gitlab/gitlab_home/config
        target: /etc/gitlab
      - type: bind
        source: ./gitlab/gitlab_home/logs
        target: /var/log/gitlab
      - type: bind
        source: ./gitlab/gitlab_home/data
        target: /var/opt/gitlab
#    profiles:
#      - run_all

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-latest}
    restart: always
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}

volumes:
  mongodb_data: { driver: local }
