services:
  ldap:
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=SigmaNet
      - LDAP_DOMAIN=sigmanet.site
      - LDAP_ADMIN_PASSWORD=Password
    volumes:
      - type: bind
        source: ./ldap/data/slapd/database
        target: /var/lib/ldap
      - type: bind
        source: ./ldap/data/slapd/config
        target: /etc/ldap/slapd.d
  ldap_admin:
    image: osixia/phpldapadmin
    ports: 
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./gitlab/gitlab_home/config
        target: /etc/gitlab
      - type: bind
        source: ./gitlab/gitlab_home/logs
        target: /var/log/gitlab
      - type: bind
        source: ./gitlab/gitlab_home/data
        target: /var/opt/gitlab
